Logbook en
i-doit/knowledge-base pull request #203
Opened 2023-08-04 09:37 UTC by dmingal

Check branches

2023-08-04 10:45 UTC, MichaelOv commented on docs/en/basics/custom-categories.md
Please also change all lists to this format:
From e.g. (* with 3 whitespaced)
`*    **Checkbox**<br>`
To (- with one whitespace)
`- **Checkbox**<br>`

2023-08-04 10:50 UTC, MichaelOv commented on docs/en/basics/custom-categories.md
In the field List, date is a duplicate, row 69

2023-08-04 10:50 UTC, MichaelOv commented on docs/en/basics/custom-categories.md
Image 8-cc is wrong

2023-08-04 10:56 UTC, MichaelOv commented on docs/en/basics/custom-object-types.md
Please also fix header from ----------- to
title of the page #
header ##
subheader ###
...

2023-08-04 10:57 UTC, MichaelOv commented on docs/en/basics/custom-object-types.md
Alsi fix lists as mentioned 
> Please also change all lists to this format: From e.g. (* with 3 whitespaced) `* **Checkbox**<br>` To (- with one whitespace) `- **Checkbox**<br>`

2023-08-04 10:57 UTC, MichaelOv commented on docs/en/basics/custom-object-types.md
Use <br> instead of (two whitespaces)

2023-08-04 11:00 UTC, MichaelOv commented on docs/en/basics/custom-object-types.md
Every page has to end with a empty single new line

2023-08-04 11:01 UTC, MichaelOv commented on docs/en/basics/dialog-admin.md
> Please also fix header from ----------- to title of the page # header ## subheader ### ...

2023-08-04 11:28 UTC, MichaelOv requested changes

2023-08-04 11:28 UTC, MichaelOv commented on docs/en/basics/dialog-admin.md
> Please also change all lists to this format: From e.g. (* with 3 whitespaced) `* **Checkbox**<br>` To (- with one whitespace) `- **Checkbox**<br>`

2023-08-04 11:28 UTC, MichaelOv commented on docs/en/basics/logbook.md
1. Please also fix header from `-----------` to 
title of the page `#`
header `##`
subheader `###` ...

2. Please also change all lists to this format: From e.g. (* with 3 whitespaced) 
`* **Checkbox**<br>` 
To (- with one whitespace) 
`- **Checkbox**<br>`

3. Use `<br>` instead of (two whitespaces)

5. Every page has to end with a `empty single new line`

2023-08-04 11:28 UTC, MichaelOv commented on docs/en/basics/dialog-admin.md
Alter line 40 to [a ](https://squidfunk.github.io/mkdocs-material/reference/admonitions/#type:warning)

2023-08-04 11:28 UTC, MichaelOv commented on docs/en/basics/logbook.md
6. For commands use the correct syntax e.g. for a shell command
`empty line before`
```shell
sudo xyz
```
`empty line after`

line 78

2023-08-04 13:05 UTC, dmingal commented on docs/en/basics/dialog-admin.md
Done

2023-08-04 13:05 UTC, dmingal commented on docs/en/basics/logbook.md
Done

2023-08-07 10:46 UTC, MichaelOv approved these changes

2023-08-07 12:31 UTC, merged