Unique-identifiers update
i-doit/knowledge-base pull request #220
Opened 2023-08-10 13:48 UTC by dmingal

2023-08-11 13:54 UTC, ljuergenliemke commented on docs/en/basics/unique-references.md
>  IP addresses are not unique per se. For example, in private networks the same addresses (192.168.1.1 etc.) recur again and again. When **[**Layer-3 networks**](../use-cases/ip-adress-management.md)**
Hier sind 4 mal '*' zu viel, bitte nur am Anfang und am ende jeweils 2 machen.

2023-08-11 14:00 UTC, ljuergenliemke requested changes
Siehe Kommentar

2023-08-18 12:07 UTC, dmingal commented
Changed

2023-08-21 08:50 UTC, ljuergenliemke approved these changes

2023-08-21 09:59 UTC, merged